### ISSUE TITLE
"Font family" to "Emoji style" and new emoji font family

### ISSUE THREAD

**Issue by rado84-github** [Sav22999/emoji#122]
Hi. First of all - I LOVE this extension! I've been using it for over a year now and it's safe to say it's one of the extensions I can't live without, mostly because social media don't have the "most frequently used" tab when it comes to emojis.

I have 2 suggestions, at least the first one should be possible to be done:

1. Instead of "Font family" in settings, change it to "Emoji style" because "font family" is confusing, especially for an extension that deals with emojis. It took me quite a while to realize that "font family" actually meant emoji style. 🤭 

2. If it's possible, can you add all the Facebook emojis? Look how different they are from the rest that are currently available.

![Picture_created_20-07-2024_19-45-19](https://github.com/user-attachments/assets/70848616-6185-4cdf-8dbd-489586ac545c)

And third, altough that's not a suggestion but a question: if I find there are missing emojis and I want them added to the collection, what do I need to do? Say, I have an image - what size(s) and format should I make that image to be useable as an emoji for this extension? And where do I send it for it to be added?

**Comment by Sav22999** [comment]
@rado84-github Hi!
First of all, I'm very happy you like the add-on and its features 😄 

Answering to your requests:
1. I'll implement an improvement about this choosing, actually, in a future update (you'll be able to select, instead of the "name" of the emoji-font-family, the "preview": something like the buttons' size)
2. This is impossible just because Facebook emoji font family is not open source, and so I cannot implement in the add-on, I'm sorry


If you find some missing emojis, please open an issue like this one reporting the emojis you've found there aren't in the add-on: you don't need to provide of picture, just list me the missing emojis

**Comment by rado84-github** [comment]
> If you find some missing emojis, please open an issue like this one reporting the emojis you've found there aren't in the add-on: you don't need to provide of picture, just list me the missing emojis

Well, there are two missing flags and I was thinking I could provide them as png or psd and you could convert them to whatever format they're necessary to function in the extension. The missing flags are those of bisexuals and lesbians. Having just the gay and trans flags is discriminatory (not blaming you, don't worry) cuz neither of us identifies as the available ones.

**Comment by Sav22999** [comment]
@rado84-github Emojis you find in the add-on are those "standardised" by UNICODE (Unicode Consortium). At the moment, the "lesbian" and the "bisexual" flags aren't available, I'm so sorry.
I hope you can understand.

To find all emojis, you can see here: https://emojipedia.org
