### ISSUE TITLE
All emojis are blank

### ISSUE THREAD

**Issue by n-apps** [Sav22999/emoji#69]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/16646251/187269684-94ff147c-6f3a-4e5a-8a78-3d5bc75f1684.png">

Click to copy/paste is working. Reinstall didn't fix it for me. Firefox v 104.0 (MacOS 12.4.1)

UPD: https://github.com/Sav22999/emoji/issues/69#issuecomment-1230690812

**Comment by Sav22999** [comment]
Please, could tell me the version of the addon?
If you change the language (in Settings), the problem persists?

**Comment by n-apps** [comment]
> Please, could tell me the version of the addon? If you change the language (in Settings), the problem persists?

Version 3.14.4. Switching language doesn't help, but when I switch from the Twitter set (font) to another one, all emojis are displayed correctly.

**Comment by Sav22999** [comment]
@n-apps this is weird 🤔🤔

**Comment by Sav22999** [comment]
@n-apps What OS do you use?
I'm investigating but I don't find the issue

**Comment by blakegearin** [comment]
Mine has looked like this for at least a couple weeks, albeit black instead of white. English typically. Changing languages doesn't seem to impact the issue.

Versions:
- `3.14.4::MFA`
- Firefox `105.0b4`
- macOS `12.4` (Monterey)

![image](https://user-images.githubusercontent.com/17950836/187732335-eed1b549-6245-40ea-8a67-66fc6c16d762.png)

**Comment by Sav22999** [comment]
Ok, it looks like the issue is only on Mac OS 🤔 
I'll send a new release with a temporary font family ("Twemoji - Temporary fix"), which will use the previous version of Twemoji

Sorry for the inconvenience

@blakegearin you say you see this issue for at least a couple of weeks... I've release the new version only 6 days ago... please, could you try to install the [3.14.3.3](https://github.com/Sav22999/emoji/releases/tag/3.14.3.3) as debug and tell me if the problem is present there too?

**Comment by blakegearin** [comment]
> could you try to install the [3.14.3.3](https://github.com/Sav22999/emoji/releases/tag/3.14.3.3) as debug and tell me if the problem is present there too?

I did this and the issue was not present.

![image](https://user-images.githubusercontent.com/17950836/187739954-9eadc749-e6a6-4dc5-9a8d-022017721ce1.png)

Also noticed that on `3.14.4` the number emojis appear like normal.

![image](https://user-images.githubusercontent.com/17950836/187739800-0238d77d-4744-4e8d-87da-a64b89233293.png)

**Comment by Sav22999** [comment]
@n-apps @blakegearin I've release today a temporary fix (3.14.4.1). The update should arrive in some hours (/tomorrow) on Firefox Add-ons

I'm so sorry about the issue

**Comment by n-apps** [comment]
> @n-apps @blakegearin Do you have still this problem using the normal font-family? I tried on many Mac and I haven't got anymore the error

v 3.15 – All good. Thanks! 🙌
